project:
  type: website
  output-dir: docs

website:
    title: "Stone Neilon"
    navbar:
        background: primary
        search: true
        left:
            - text: "CV"
              href: https://drive.google.com/file/d/1RgKR73KnxS3K_AP2nqiTiZZzAL-zJZ2N/view?usp=sharing
            - text: "Blog"
              href: posts.html
            - text: "Teaching" 
              href: teaching.html
            - text: "Research"
              href: research.html
            - text: "Notes" 
              href: notes.html

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

